{"uid":"4d897dc3090beb4a","name":"should propagate asynchronous error with scope","fullName":"test/Publish.test.ts#Publish Mechanism Error propagation Async errors with scope should propagate asynchronous error with scope","historyId":"5225966a5e8207887c5027e309da982d:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1743018241582,"stop":1743018241605,"duration":23},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"framework","value":"vitest"},{"name":"language","value":"javascript"},{"name":"parentSuite","value":"Publish Mechanism"},{"name":"suite","value":"Error propagation"},{"name":"subSuite","value":"Async errors with scope"},{"name":"host","value":"fv-az1938-282"},{"name":"thread","value":"vitest-worker-1"},{"name":"package","value":"test.Publish.test.ts"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":[]},"source":"4d897dc3090beb4a.json","parameterValues":[]}