{"uid":"caf1a3332eb7ecd5","name":"should propagate asynchronous error","fullName":"test/Publish.test.ts#Publish Mechanism Error propagation Async errors without scope should propagate asynchronous error","historyId":"07b048da47639beff38cccac4e874975:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1743018241546,"stop":1743018241560,"duration":14},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"framework","value":"vitest"},{"name":"language","value":"javascript"},{"name":"parentSuite","value":"Publish Mechanism"},{"name":"suite","value":"Error propagation"},{"name":"subSuite","value":"Async errors without scope"},{"name":"host","value":"fv-az1938-282"},{"name":"thread","value":"vitest-worker-1"},{"name":"package","value":"test.Publish.test.ts"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":[]},"source":"caf1a3332eb7ecd5.json","parameterValues":[]}