{"uid":"d4faa9c706a36970","name":"should propagate synchronous error with scope","fullName":"test/Publish.test.ts#Publish Mechanism Error propagation Non-async errors with scope should propagate synchronous error with scope","historyId":"cf80a63b2b0129cad9d4b86a52ff4463:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1743018241560,"stop":1743018241582,"duration":22},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"framework","value":"vitest"},{"name":"language","value":"javascript"},{"name":"parentSuite","value":"Publish Mechanism"},{"name":"suite","value":"Error propagation"},{"name":"subSuite","value":"Non-async errors with scope"},{"name":"host","value":"fv-az1938-282"},{"name":"thread","value":"vitest-worker-1"},{"name":"package","value":"test.Publish.test.ts"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":[]},"source":"d4faa9c706a36970.json","parameterValues":[]}